config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'

  resources :courses
  resources :students, except: [:destroy]
  get 'about', to: 'pages#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'course_enroll', to: 'student_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, presence: true, length: { minimum: 5, maximum: 20}
    validates :code, presence: true, length: { minimum: 3, maximum: 6}
    validates :description, presence: true, length: { minimum: 10, maximum: 300}

    has_many :student_courses
    has_many :students, through: :student_courses 
end

app/models/student.rb
class Student < ApplicationRecord

    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { minimum: 5, maximum: 20}
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 100 },
						uniqueness: { case_sensitive: false},
                        format: { with: VALID_EMAIL_REGEX }
                        
    has_secure_password

    has_many :student_courses
    has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :require_user

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= Student.find(session[:student_id]) if session[:student_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:notice] = "Login to perform action"
            redirect_to login_path
        end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    skip_before_action :require_user

    def index
        @courses = Course.all
    end

    def new

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :require_user

    def about

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]

    def new

    end

    def create
        student = Student.find_by(email: params[:sessions][:email].downcase)
        if student && student.authenticate(params[:sessions][:password])
            session[:student_id] = student.id
            flash[:success] = "Welcome!"
            redirect_to student
        else
            flash.now[:error] = 'Incorrect email or password'
            render 'new'
        end
    end

    def destroy
        session[:student_id] = nil
        flash[:success] = "Successfully logged out"
        redirect_to root_path
    end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController

    def create
        course = Course.find(params[:course_id])
        unless current_user.courses.include?(course)
            StudentCourse.create(course: course, student: current_user)
            flash[:notice] = "You have successfully enrolled in #{course.name}"
            redirect_to current_user
        else
            flash[:notice] = "Something wrong happened"
            redirect_to root_path
        end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]
    before_action :set_student, except: [:index, :new, :create]
    before_action :require_permission, only: [:edit, :update]

    def index
        @students = Student.all
    end

    def show
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            flash[:success] = "account created"
            redirect_to @student
        else
            render 'new'
        end
    end

    def edit

    end

    def update
        if @student.update(student_params)
            flash[:notice] = "Profile successfully updated."
            redirect_to @student
        else
            render 'edit'
        end
    end

    private

    def require_permission
        if current_user != @student
            flash[:error] = "You don't have permission to perform this action"
            redirect_to student_path(current_user)
        end
    end

    def set_student
        @student = Student.find(params[:id])
    end

    def student_params
        params.require(:student).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def session_link
        if logged_in?
            link_to 'logout', logout_path, method: :delete
        else
            link_to 'login', login_path
        end
    end
end

app/views/courses/index.html.erb
<div class='row'>
    <div class='col s12'>
        <h3 class='center-align'>Course listing</h3>
    </div>
</div>

<div class="row">
    <% @courses.each do |course| %>
        <div class="col s6 m6">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title"><%= course.code %>: <%= course.name %> </span>
                    <p><%= course.description %></p>
                </div>
                <div class="card-action">
                    <% if logged_in? && !current_user.courses.include?(course) %>
                        <%= link_to 'Enroll', course_enroll_path(course_id: course.id), method: :post %>
                    <% end %>
                    <a href="#">Info</a>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/courses/new.html.erb
new course page

app/views/layouts/_footer.html.erb
<div class="container">
    <div class="row">
        <div class="col l6 s12">
            <h5 class="white-text">UniversityApp</h5>
            <p class="grey-text text-lighten-4">asd</p>
        </div>
        <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Information</h5>
            <ul>
                <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="footer-copyright">
    <div class="container">
        © 2019 UniversityApp
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<ul id="dropdown1" class="dropdown-content">
    <li><%= session_link %></li>
    <%if logged_in? %>
        <li><%= link_to 'My Profile', student_path(current_user)%></li>
    <% end %>
    <li class="divider"></li>
</ul>
<ul id="dropdown2" class="dropdown-content">
    <li><%= session_link %></li>
    <%if logged_in? %>
        <li><%= link_to 'My Profile', student_path(current_user)%></li>
    <% end %>
    <li class="divider"></li>
</ul>
<nav>
    <div class='container'>
        <div class="nav-wrapper">
        <%= link_to 'UniversityApp', root_path, class:"brand-logo" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to 'Courses', root_path %></li>
            <% if logged_in? %>
                <li><%= link_to 'Students', students_path %></li>
            <% end %>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <ul class="sidenav" id="mobile-demo">
            <li><%= link_to 'Courses', root_path %></li>
            <% if logged_in? %>
                <li><%= link_to 'Students', students_path %></li>
            <% end %>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniversityApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <% flash.each do |key, message| %>
        <div class='container'>
          <div class='row-center sign-up-form'>
              <div class='col s12 m12 l12'>
                  <div class='card-panel red base' id='fade-out-target'>
                      <span class='white-text'>
                          <%= message %>
                      </span>
                  </div>
              </div>
          </div>
        <% end %>
      </div>
    </header>
    <main>
      <div class='container'>
        <%= yield %>
      </div>
    </main>
    <footer class="page-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
about page

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class='container'>
        <div class='row-center sign-up-form'>
            <div class='col s12 m12 l12'>
                <div class='card-panel red base'>
                    <span class='white-text'>
                        <strong><%= pluralize(obj.errors.count, "error") %></strong>
                        <ul>
                            <% obj.errors.full_messages.each do |error| %>
                                <li><%= error %></li>
                            <% end %>
                        </ul>
                    </span>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class='container'>
    <div class='row-center sign-up-form'>
        <div class='col s12 m12 l12'>
            <div class='card-panel'>
                <div class='row'>
                    <div class='col s12'>
                        <h3 class='center-align'><%= @student.new_record? ? 'Sign up' : 'Edit your profile' %></h3>
                    </div>
                </div>
                <div class='row'>
                    <%= form_for(@student, html: {class: 'col s12'}) do |f| %>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <%= f.label :name %>
                                <%= f.text_field :name, placeholder: "Full name", autofocus: true %>
                            </div>
                        </div>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <%= f.label :email, class: 'active' %>
                                <%= f.email_field :email %>
                            </div>
                        </div>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <%= f.label :password, class: 'active' %>
                                <%= f.password_field :password %>
                            </div>
                        </div>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <%= f.label :password_confirmation, class: 'active' %>
                                <%= f.password_field :password_confirmation, placeholder: 'confirm your password' %>
                            </div>
                        </div>
                        <%= f.button(@student.new_record? ? 'Sign up' : 'Submit changes', class: 'btn waves-effect waves-light right') %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class='row'>
    <div class='col s12'>
        <h3 class='center-align'>Students</h3>
    </div>
</div>

<div class="row">
    <% @students.each do |student| %>
        <div class="col s6 m6">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">Name: <%= student.name %> </span>
                    <p>Email: <%= student.email %> </p>
                </div>
                <div class="card-action">
                    <%= link_to 'Profile', student_path(student) %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/students/new.html.erb
<% if @student.errors.any? %>
    <div class='container'>
        <div class='row-center sign-up-form'>
            <div class='col s12 m12 l12'>
                <div class='card-panel red base'>
                    <span class='white-text'>
                        <strong><%= pluralize(@student.errors.count, "error") %></strong>
                        <ul>
                            <% @student.errors.full_messages.each do |error| %>
                                <li><%= error %></li>
                            <% end %>
                        </ul>
                    </span>
                </div>
            </div>
        </div>
    </div>
<% end %>

<div class='container'>
    <div class='row-center sign-up-form'>
        <div class='col s12 m12 l12'>
            <div class='card-panel'>
                <div class='row'>
                    <div class='col s12'>
                        <h3 class='center-align'>Sign up</h3>
                    </div>
                </div>
                <div class='row'>
                    <%= form_for(@student, html: {class: 'col s12'}) do |f| %>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <%= f.label :name %>
                                <%= f.text_field :name, placeholder: "Full name", autofocus: true %>
                            </div>
                        </div>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <%= f.label :email %>
                                <%= f.text_field :email %>
                            </div>
                        </div>
                        <%= f.submit 'Sign up', class: 'btn waves-effect waves-light right' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/show.html.erb
<div class="row sign-up-form">
    <div class="col s6 m6">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title">Name: <%= @student.name %> </span>
                <p>Email: <%= @student.email %> </p>
                <p>Course enrollments: 
                    <% if @student.courses.empty? %>
                        None
                    <% else %>
                        <ul>
                            <% @student.courses.each do |course| %>
                                <li><%= course.name %></li>
                            <% end %>
                        </ul>
                    <% end %>
                </p>
            </div>
        </div>
        <% if current_user == @student %>
            <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
        <% end %>
    </div>
</div>